# 공공데이터 활용

- https://www.data.go.kr/  
- 승인받아야함.

- 사용할 패키지 호출

- API이용시 필요한 정보 입력

In [38]:
LAWD_CD = "11110"
DEAL_YMD = "201512"
serviceKey  = "MMc9HcZzSMSfwjnS1gBUFHq2Fb6sPHLarVx%2Boi9seEd3qUGzYUR4PhshZS9Sd06k0DNjdHwRdSW1qOLY5psDDw%3D%3D"
url = "http://openapi.molit.go.kr:8081/OpenAPI_ToolInstallPackage/service/rest/RTMSOBJSvc/getRTMSDataSvcAptTrade?LAWD_CD={}&DEAL_YMD={}&serviceKey={}".format(LAWD_CD,DEAL_YMD,serviceKey)

- 패키지내 함수를 이용해 API 호출

In [39]:
import urllib
from bs4 import BeautifulSoup
import requests

In [40]:
import pandas as pd
import numpy as np

## 목표 설정

In [41]:
result = urllib.request.urlopen(url)

In [42]:
soup = BeautifulSoup(result,"xml")

In [43]:
items = soup.findAll("item")

In [44]:
keylist = ["거래금액","건축년도","년","법정동","아파트","월","일","전용면적","지번","지역코드","층"]

In [45]:
itemlist = []

In [46]:
for v in items:
    item = {}
    
    for key in keylist:
        try:
            item[key] = v.find(key).text
        except :
            item[key] = np.nan
    itemlist.append(item)

In [47]:
itemlist

[{'거래금액': '    82,500',
  '건축년도': '2008',
  '년': '2015',
  '법정동': ' 사직동',
  '아파트': '광화문풍림스페이스본(101동~105동)',
  '월': '12',
  '일': '10',
  '전용면적': '94.51',
  '지번': '9',
  '지역코드': '11110',
  '층': '11'},
 {'거래금액': '    60,000',
  '건축년도': '1981',
  '년': '2015',
  '법정동': ' 당주동',
  '아파트': '롯데미도파광화문빌딩',
  '월': '12',
  '일': '22',
  '전용면적': '149.95',
  '지번': '145',
  '지역코드': '11110',
  '층': '8'},
 {'거래금액': '   130,000',
  '건축년도': '2004',
  '년': '2015',
  '법정동': ' 내수동',
  '아파트': '킹스매너',
  '월': '12',
  '일': '8',
  '전용면적': '194.43',
  '지번': '110-15',
  '지역코드': '11110',
  '층': '6'},
 {'거래금액': '   105,000',
  '건축년도': '2004',
  '년': '2015',
  '법정동': ' 내수동',
  '아파트': '경희궁의아침2단지',
  '월': '12',
  '일': '14',
  '전용면적': '124.17',
  '지번': '71',
  '지역코드': '11110',
  '층': '8'},
 {'거래금액': '   120,000',
  '건축년도': '2003',
  '년': '2015',
  '법정동': ' 내수동',
  '아파트': '경희궁 파크팰리스',
  '월': '12',
  '일': '24',
  '전용면적': '146.33',
  '지번': '95',
  '지역코드': '11110',
  '층': '4'},
 {'거래금액': '    17,000',
  '건축년도': '2014',
  '년': '2015',
  '법정동': ' 연건동',
  '아파트': '이화에수풀',
  '월': '12',
  '일': '17',
  '전용면적': '16.98',
  '지번': '195-10',
  '지역코드': '11110',
  '층': '8'},
 {'거래금액': '    17,000',
  '건축년도': '2014',
  '년': '2015',
  '법정동': ' 연건동',
  '아파트': '이화에수풀',
  '월': '12',
  '일': '18',
  '전용면적': '16.98',
  '지번': '195-10',
  '지역코드': '11110',
  '층': '4'},
 {'거래금액': '    57,000',
  '건축년도': '2006',
  '년': '2015',
  '법정동': ' 명륜1가',
  '아파트': '렉스빌',
  '월': '12',
  '일': '29',
  '전용면적': '106.98',
  '지번': '19',
  '지역코드': '11110',
  '층': '3'},
 {'거래금액': '    44,000',
  '건축년도': '1995',
  '년': '2015',
  '법정동': ' 명륜2가',
  '아파트': '아남1',
  '월': '12',
  '일': '1',
  '전용면적': '84.8',
  '지번': '4',
  '지역코드': '11110',
  '층': '18'},
 {'거래금액': '    52,000',
  '건축년도': '1995',
  '년': '2015',
  '법정동': ' 명륜2가',
  '아파트': '아남1',
  '월': '12',
  '일': '10',
  '전용면적': '84.9',
  '지번': '4',
  '지역코드': '11110',
  '층': '12'},
 {'거래금액': '    49,800',
  '건축년도': '1995',
  '년': '2015',
  '법정동': ' 명륜2가',
  '아파트': '아남1',
  '월': '12',
  '일': '19',
  '전용면적': '84.8',
  '지번': '4',
  '지역코드': '11110',
  '층': '1'},
 {'거래금액': '    41,000',
  '건축년도': '1999',
  '년': '2015',
  '법정동': ' 명륜2가',
  '아파트': '아남3',
  '월': '12',
  '일': '19',
  '전용면적': '61.13',
  '지번': '237',
  '지역코드': '11110',
  '층': '7'},
 {'거래금액': '    41,000',
  '건축년도': '1999',
  '년': '2015',
  '법정동': ' 창신동',
  '아파트': '두산',
  '월': '12',
  '일': '2',
  '전용면적': '59.95',
  '지번': '232',
  '지역코드': '11110',
  '층': '9'},
 {'거래금액': '    39,900',
  '건축년도': '2003',
  '년': '2015',
  '법정동': ' 창신동',
  '아파트': '창신이수',
  '월': '12',
  '일': '3',
  '전용면적': '68.06',
  '지번': '23-816',
  '지역코드': '11110',
  '층': '8'},
 {'거래금액': '    19,500',
  '건축년도': '1966',
  '년': '2015',
  '법정동': ' 창신동',
  '아파트': '동대문',
  '월': '12',
  '일': '3',
  '전용면적': '28.8',
  '지번': '328-17',
  '지역코드': '11110',
  '층': '6'},
 {'거래금액': '    20,800',
  '건축년도': '1966',
  '년': '2015',
  '법정동': ' 창신동',
  '아파트': '동대문',
  '월': '12',
  '일': '7',
  '전용면적': '28.8',
  '지번': '328-17',
  '지역코드': '11110',
  '층': '3'},
 {'거래금액': '    27,200',
  '건축년도': '1993',
  '년': '2015',
  '법정동': ' 창신동',
  '아파트': '창신쌍용2',
  '월': '12',
  '일': '7',
  '전용면적': '64.66',
  '지번': '703',
  '지역코드': '11110',
  '층': '3'},
 {'거래금액': '    39,000',
  '건축년도': '1999',
  '년': '2015',
  '법정동': ' 창신동',
  '아파트': '두산',
  '월': '12',
  '일': '10',
  '전용면적': '59.95',
  '지번': '232',
  '지역코드': '11110',
  '층': '14'},
 {'거래금액': '    39,950',
  '건축년도': '1993',
  '년': '2015',
  '법정동': ' 창신동',
  '아파트': '창신쌍용2',
  '월': '12',
  '일': '11',
  '전용면적': '115.53',
  '지번': '703',
  '지역코드': '11110',
  '층': '2'},
 {'거래금액': '    34,500',
  '건축년도': '1992',
  '년': '2015',
  '법정동': ' 창신동',
  '아파트': '창신쌍용1',
  '월': '12',
  '일': '12',
  '전용면적': '79.87',
  '지번': '702',
  '지역코드': '11110',
  '층': '5'},
 {'거래금액': '    37,000',
  '건축년도': '1992',
  '년': '2015',
  '법정동': ' 창신동',
  '아파트': '창신쌍용1',
  '월': '12',
  '일': '14',
  '전용면적': '79.87',
  '지번': '702',
  '지역코드': '11110',
  '층': '3'},
 {'거래금액': '    42,800',
  '건축년도': '1992',
  '년': '2015',
  '법정동': ' 창신동',
  '아파트': '창신쌍용1',
  '월': '12',
  '일': '22',
  '전용면적': '106.62',
  '지번': '702',
  '지역코드': '11110',
  '층': '12'},
 {'거래금액': '    37,300',
  '건축년도': '1992',
  '년': '2015',
  '법정동': ' 창신동',
  '아파트': '창신쌍용1',
  '월': '12',
  '일': '23',
  '전용면적': '79.87',
  '지번': '702',
  '지역코드': '11110',
  '층': '9'},
 {'거래금액': '    50,000',
  '건축년도': '1999',
  '년': '2015',
  '법정동': ' 창신동',
  '아파트': '두산',
  '월': '12',
  '일': '24',
  '전용면적': '84.9',
  '지번': '232',
  '지역코드': '11110',
  '층': '4'},
 {'거래금액': '    12,300',
  '건축년도': '2013',
  '년': '2015',
  '법정동': ' 숭인동',
  '아파트': '종로아인스빌',
  '월': '12',
  '일': '2',
  '전용면적': '12.15',
  '지번': '1392-1',
  '지역코드': '11110',
  '층': '10'},
 {'거래금액': '    52,000',
  '건축년도': '2009',
  '년': '2015',
  '법정동': ' 숭인동',
  '아파트': '종로청계힐스테이트',
  '월': '12',
  '일': '3',
  '전용면적': '84.9478',
  '지번': '766',
  '지역코드': '11110',
  '층': '19'},
 {'거래금액': '    42,500',
  '건축년도': '2009',
  '년': '2015',
  '법정동': ' 숭인동',
  '아파트': '종로청계힐스테이트',
  '월': '12',
  '일': '5',
  '전용면적': '59.9426',
  '지번': '766',
  '지역코드': '11110',
  '층': '2'},
 {'거래금액': '    53,300',
  '건축년도': '2008',
  '년': '2015',
  '법정동': ' 숭인동',
  '아파트': '종로센트레빌',
  '월': '12',
  '일': '5',
  '전용면적': '84.92',
  '지번': '2-1',
  '지역코드': '11110',
  '층': '10'},
 {'거래금액': '    11,500',
  '건축년도': '2014',
  '년': '2015',
  '법정동': ' 숭인동',
  '아파트': '숭인한양LEEPS',
  '월': '12',
  '일': '8',
  '전용면적': '12.78',
  '지번': '1421-2',
  '지역코드': '11110',
  '층': '10'},
 {'거래금액': '    13,000',
  '건축년도': '2014',
  '년': '2015',
  '법정동': ' 숭인동',
  '아파트': '삼전솔하임4차',
  '월': '12',
  '일': '8',
  '전용면적': '15.09',
  '지번': '318-2',
  '지역코드': '11110',
  '층': '15'},
 {'거래금액': '    27,000',
  '건축년도': '1997',
  '년': '2015',
  '법정동': ' 숭인동',
  '아파트': '동문 (비동,씨동) (494-0)',
  '월': '12',
  '일': '9',
  '전용면적': '59.94',
  '지번': '494',
  '지역코드': '11110',
  '층': '3'},
 {'거래금액': '    44,900',
  '건축년도': '2009',
  '년': '2015',
  '법정동': ' 숭인동',
  '아파트': '종로청계힐스테이트',
  '월': '12',
  '일': '14',
  '전용면적': '59.9426',
  '지번': '766',
  '지역코드': '11110',
  '층': '12'},
 {'거래금액': '    11,900',
  '건축년도': '2014',
  '년': '2015',
  '법정동': ' 숭인동',
  '아파트': '숭인한양LEEPS',
  '월': '12',
  '일': '14',
  '전용면적': '12.78',
  '지번': '1421-2',
  '지역코드': '11110',
  '층': '11'},
 {'거래금액': '    10,000',
  '건축년도': '2013',
  '년': '2015',
  '법정동': ' 숭인동',
  '아파트': '주건축물제1동',
  '월': '12',
  '일': '15',
  '전용면적': '14.48',
  '지번': '1392',
  '지역코드': '11110',
  '층': '14'},
 {'거래금액': '    10,500',
  '건축년도': '2013',
  '년': '2015',
  '법정동': ' 숭인동',
  '아파트': '주건축물제1동',
  '월': '12',
  '일': '15',
  '전용면적': '15.76',
  '지번': '1392',
  '지역코드': '11110',
  '층': '13'},
 {'거래금액': '    42,500',
  '건축년도': '2008',
  '년': '2015',
  '법정동': ' 숭인동',
  '아파트': '종로센트레빌',
  '월': '12',
  '일': '19',
  '전용면적': '59.92',
  '지번': '2-1',
  '지역코드': '11110',
  '층': '12'},
 {'거래금액': '    39,700',
  '건축년도': '2008',
  '년': '2015',
  '법정동': ' 숭인동',
  '아파트': '종로센트레빌',
  '월': '12',
  '일': '22',
  '전용면적': '59.92',
  '지번': '2-1',
  '지역코드': '11110',
  '층': '1'},
 {'거래금액': '    52,300',
  '건축년도': '2008',
  '년': '2015',
  '법정동': ' 숭인동',
  '아파트': '종로센트레빌',
  '월': '12',
  '일': '26',
  '전용면적': '84.92',
  '지번': '2-1',
  '지역코드': '11110',
  '층': '12'},
 {'거래금액': '    10,800',
  '건축년도': '2013',
  '년': '2015',
  '법정동': ' 숭인동',
  '아파트': '종로유케이201',
  '월': '12',
  '일': '31',
  '전용면적': '12.01',
  '지번': '201-11',
  '지역코드': '11110',
  '층': '7'},
 {'거래금액': '    52,500',
  '건축년도': '2009',
  '년': '2015',
  '법정동': ' 숭인동',
  '아파트': '종로청계힐스테이트',
  '월': '12',
  '일': '31',
  '전용면적': '84.9478',
  '지번': '766',
  '지역코드': '11110',
  '층': '11'},
 {'거래금액': '    44,600',
  '건축년도': '1995',
  '년': '2015',
  '법정동': ' 교북동',
  '아파트': '동아',
  '월': '12',
  '일': '7',
  '전용면적': '84.28',
  '지번': '101',
  '지역코드': '11110',
  '층': '10'},
 {'거래금액': '   115,000',
  '건축년도': '2004',
  '년': '2015',
  '법정동': ' 평창동',
  '아파트': '벽산블루밍평창힐스',
  '월': '12',
  '일': '2',
  '전용면적': '210.53',
  '지번': '45',
  '지역코드': '11110',
  '층': '2'},
 {'거래금액': '   164,500',
  '건축년도': '2009',
  '년': '2015',
  '법정동': ' 평창동',
  '아파트': '롯데캐슬 로잔',
  '월': '12',
  '일': '3',
  '전용면적': '219.775',
  '지번': '108',
  '지역코드': '11110',
  '층': '3'},
 {'거래금액': '    31,500',
  '건축년도': '1998',
  '년': '2015',
  '법정동': ' 평창동',
  '아파트': '삼성',
  '월': '12',
  '일': '6',
  '전용면적': '59.97',
  '지번': '596',
  '지역코드': '11110',
  '층': '9'},
 {'거래금액': '    39,490',
  '건축년도': '2000',
  '년': '2015',
  '법정동': ' 무악동',
  '아파트': '현대',
  '월': '12',
  '일': '12',
  '전용면적': '60',
  '지번': '82',
  '지역코드': '11110',
  '층': '15'},
 {'거래금액': '    63,490',
  '건축년도': '2000',
  '년': '2015',
  '법정동': ' 무악동',
  '아파트': '현대',
  '월': '12',
  '일': '15',
  '전용면적': '114.9',
  '지번': '82',
  '지역코드': '11110',
  '층': '6'},
 {'거래금액': '    62,000',
  '건축년도': '2008',
  '년': '2015',
  '법정동': ' 무악동',
  '아파트': '인왕산아이파크',
  '월': '12',
  '일': '16',
  '전용면적': '84.858',
  '지번': '60',
  '지역코드': '11110',
  '층': '5'},
 {'거래금액': '    63,400',
  '건축년도': '2015',
  '년': '2015',
  '법정동': ' 무악동',
  '아파트': '인왕산2차아이파크',
  '월': '12',
  '일': '22',
  '전용면적': '84.0284',
  '지번': '88',
  '지역코드': '11110',
  '층': '10'},
 {'거래금액': '    61,000',
  '건축년도': '2008',
  '년': '2015',
  '법정동': ' 무악동',
  '아파트': '인왕산아이파크',
  '월': '12',
  '일': '25',
  '전용면적': '84.858',
  '지번': '60',
  '지역코드': '11110',
  '층': '13'}]

In [48]:
df = pd.DataFrame(itemlist)

In [49]:
df

,거래금액,건축년도,년,법정동,아파트,월,일,전용면적,지번,지역코드,층
0,"82,500",2008,2015,사직동,광화문풍림스페이스본(101동~105동),12,10,94.51,9,11110,11
1,"60,000",1981,2015,당주동,롯데미도파광화문빌딩,12,22,149.95,145,11110,8
2,"130,000",2004,2015,내수동,킹스매너,12,8,194.43,110-15,11110,6
3,"105,000",2004,2015,내수동,경희궁의아침2단지,12,14,124.17,71,11110,8
4,"120,000",2003,2015,내수동,경희궁 파크팰리스,12,24,146.33,95,11110,4
5,"17,000",2014,2015,연건동,이화에수풀,12,17,16.98,195-10,11110,8
6,"17,000",2014,2015,연건동,이화에수풀,12,18,16.98,195-10,11110,4
7,"57,000",2006,2015,명륜1가,렉스빌,12,29,106.98,19,11110,3
8,"44,000",1995,2015,명륜2가,아남1,12,1,84.8,4,11110,18
9,"52,000",1995,2015,명륜2가,아남1,12,10,84.9,4,11110,12
10,"49,800",1995,2015,명륜2가,아남1,12,19,84.8,4,11110,1
11,"41,000",1999,2015,명륜2가,아남3,12,19,61.13,237,11110,7
12,"41,000",1999,2015,창신동,두산,12,2,59.95,232,11110,9
13,"39,900",2003,2015,창신동,창신이수,12,3,68.06,23-816,11110,8
14,"19,500",1966,2015,창신동,동대문,12,3,28.8,328-17,11110,6
15,"20,800",1966,2015,창신동,동대문,12,7,28.8,328-17,11110,3
16,"27,200",1993,2015,창신동,창신쌍용2,12,7,64.66,703,11110,3
17,"39,000",1999,2015,창신동,두산,12,10,59.95,232,11110,14
18,"39,950",1993,2015,창신동,창신쌍용2,12,11,115.53,703,11110,2
19,"34,500",1992,2015,창신동,창신쌍용1,12,12,79.87,702,11110,5
20,"37,000",1992,2015,창신동,창신쌍용1,12,14,79.87,702,11110,3
21,"42,800",1992,2015,창신동,창신쌍용1,12,22,106.62,702,11110,12
22,"37,300",1992,2015,창신동,창신쌍용1,12,23,79.87,702,11110,9
23,"50,000",1999,2015,창신동,두산,12,24,84.9,232,11110,4
24,"12,300",2013,2015,숭인동,종로아인스빌,12,2,12.15,1392-1,11110,10
25,"52,000",2009,2015,숭인동,종로청계힐스테이트,12,3,84.9478,766,11110,19
26,"42,500",2009,2015,숭인동,종로청계힐스테이트,12,5,59.9426,766,11110,2
27,"53,300",2008,2015,숭인동,종로센트레빌,12,5,84.92,2-1,11110,10
28,"11,500",2014,2015,숭인동,숭인한양LEEPS,12,8,12.78,1421-2,11110,10
29,"13,000",2014,2015,숭인동,삼전솔하임4차,12,8,15.09,318-2,11110,15
30,"27,000",1997,2015,숭인동,"동문 (비동,씨동) (494-0)",12,9,59.94,494,11110,3
31,"44,900",2009,2015,숭인동,종로청계힐스테이트,12,14,59.9426,766,11110,12
32,"11,900",2014,2015,숭인동,숭인한양LEEPS,12,14,12.78,1421-2,11110,11
33,"10,000",2013,2015,숭인동,주건축물제1동,12,15,14.48,1392,11110,14
34,"10,500",2013,2015,숭인동,주건축물제1동,12,15,15.76,1392,11110,13
35,"42,500",2008,2015,숭인동,종로센트레빌,12,19,59.92,2-1,11110,12
36,"39,700",2008,2015,숭인동,종로센트레빌,12,22,59.92,2-1,11110,1
37,"52,300",2008,2015,숭인동,종로센트레빌,12,26,84.92,2-1,11110,12
38,"10,800",2013,2015,숭인동,종로유케이201,12,31,12.01,201-11,11110,7
39,"52,500",2009,2015,숭인동,종로청계힐스테이트,12,31,84.9478,766,11110,11
40,"44,600",1995,2015,교북동,동아,12,7,84.28,101,11110,10
41,"115,000",2004,2015,평창동,벽산블루밍평창힐스,12,2,210.53,45,11110,2
42,"164,500",2009,2015,평창동,롯데캐슬 로잔,12,3,219.775,108,11110,3
43,"31,500",1998,2015,평창동,삼성,12,6,59.97,596,11110,9
44,"39,490",2000,2015,무악동,현대,12,12,60,82,11110,15
45,"63,490",2000,2015,무악동,현대,12,15,114.9,82,11110,6
46,"62,000",2008,2015,무악동,인왕산아이파크,12,16,84.858,60,11110,5
47,"63,400",2015,2015,무악동,인왕산2차아이파크,12,22,84.0284,88,11110,10
48,"61,000",2008,2015,무악동,인왕산아이파크,12,25,84.858,60,11110,13

In [50]:
df["거래금액"].values[0]

'    82,500'

In [51]:
value='    82,500'

In [52]:
value=value.replace(",","")
value=value.replace(" ","")
value

'82500'

In [53]:
df["거래금액"]=df["거래금액"].apply(lambda x:x.replace(",","").replace(" ",""))

In [54]:
df["거래금액"]=df["거래금액"].astype(np.int)

In [55]:
df

,거래금액,건축년도,년,법정동,아파트,월,일,전용면적,지번,지역코드,층
0,82500,2008,2015,사직동,광화문풍림스페이스본(101동~105동),12,10,94.51,9,11110,11
1,60000,1981,2015,당주동,롯데미도파광화문빌딩,12,22,149.95,145,11110,8
2,130000,2004,2015,내수동,킹스매너,12,8,194.43,110-15,11110,6
3,105000,2004,2015,내수동,경희궁의아침2단지,12,14,124.17,71,11110,8
4,120000,2003,2015,내수동,경희궁 파크팰리스,12,24,146.33,95,11110,4
5,17000,2014,2015,연건동,이화에수풀,12,17,16.98,195-10,11110,8
6,17000,2014,2015,연건동,이화에수풀,12,18,16.98,195-10,11110,4
7,57000,2006,2015,명륜1가,렉스빌,12,29,106.98,19,11110,3
8,44000,1995,2015,명륜2가,아남1,12,1,84.8,4,11110,18
9,52000,1995,2015,명륜2가,아남1,12,10,84.9,4,11110,12
10,49800,1995,2015,명륜2가,아남1,12,19,84.8,4,11110,1
11,41000,1999,2015,명륜2가,아남3,12,19,61.13,237,11110,7
12,41000,1999,2015,창신동,두산,12,2,59.95,232,11110,9
13,39900,2003,2015,창신동,창신이수,12,3,68.06,23-816,11110,8
14,19500,1966,2015,창신동,동대문,12,3,28.8,328-17,11110,6
15,20800,1966,2015,창신동,동대문,12,7,28.8,328-17,11110,3
16,27200,1993,2015,창신동,창신쌍용2,12,7,64.66,703,11110,3
17,39000,1999,2015,창신동,두산,12,10,59.95,232,11110,14
18,39950,1993,2015,창신동,창신쌍용2,12,11,115.53,703,11110,2
19,34500,1992,2015,창신동,창신쌍용1,12,12,79.87,702,11110,5
20,37000,1992,2015,창신동,창신쌍용1,12,14,79.87,702,11110,3
21,42800,1992,2015,창신동,창신쌍용1,12,22,106.62,702,11110,12
22,37300,1992,2015,창신동,창신쌍용1,12,23,79.87,702,11110,9
23,50000,1999,2015,창신동,두산,12,24,84.9,232,11110,4
24,12300,2013,2015,숭인동,종로아인스빌,12,2,12.15,1392-1,11110,10
25,52000,2009,2015,숭인동,종로청계힐스테이트,12,3,84.9478,766,11110,19
26,42500,2009,2015,숭인동,종로청계힐스테이트,12,5,59.9426,766,11110,2
27,53300,2008,2015,숭인동,종로센트레빌,12,5,84.92,2-1,11110,10
28,11500,2014,2015,숭인동,숭인한양LEEPS,12,8,12.78,1421-2,11110,10
29,13000,2014,2015,숭인동,삼전솔하임4차,12,8,15.09,318-2,11110,15
30,27000,1997,2015,숭인동,"동문 (비동,씨동) (494-0)",12,9,59.94,494,11110,3
31,44900,2009,2015,숭인동,종로청계힐스테이트,12,14,59.9426,766,11110,12
32,11900,2014,2015,숭인동,숭인한양LEEPS,12,14,12.78,1421-2,11110,11
33,10000,2013,2015,숭인동,주건축물제1동,12,15,14.48,1392,11110,14
34,10500,2013,2015,숭인동,주건축물제1동,12,15,15.76,1392,11110,13
35,42500,2008,2015,숭인동,종로센트레빌,12,19,59.92,2-1,11110,12
36,39700,2008,2015,숭인동,종로센트레빌,12,22,59.92,2-1,11110,1
37,52300,2008,2015,숭인동,종로센트레빌,12,26,84.92,2-1,11110,12
38,10800,2013,2015,숭인동,종로유케이201,12,31,12.01,201-11,11110,7
39,52500,2009,2015,숭인동,종로청계힐스테이트,12,31,84.9478,766,11110,11
40,44600,1995,2015,교북동,동아,12,7,84.28,101,11110,10
41,115000,2004,2015,평창동,벽산블루밍평창힐스,12,2,210.53,45,11110,2
42,164500,2009,2015,평창동,롯데캐슬 로잔,12,3,219.775,108,11110,3
43,31500,1998,2015,평창동,삼성,12,6,59.97,596,11110,9
44,39490,2000,2015,무악동,현대,12,12,60,82,11110,15
45,63490,2000,2015,무악동,현대,12,15,114.9,82,11110,6
46,62000,2008,2015,무악동,인왕산아이파크,12,16,84.858,60,11110,5
47,63400,2015,2015,무악동,인왕산2차아이파크,12,22,84.0284,88,11110,10
48,61000,2008,2015,무악동,인왕산아이파크,12,25,84.858,60,11110,13

In [58]:
#1. 년도별 아파트 가격평균
df["년"] = pd.to_numeric(df["년"])
df

,거래금액,건축년도,년,법정동,아파트,월,일,전용면적,지번,지역코드,층
0,82500,2008,2015,사직동,광화문풍림스페이스본(101동~105동),12,10,94.51,9,11110,11
1,60000,1981,2015,당주동,롯데미도파광화문빌딩,12,22,149.95,145,11110,8
2,130000,2004,2015,내수동,킹스매너,12,8,194.43,110-15,11110,6
3,105000,2004,2015,내수동,경희궁의아침2단지,12,14,124.17,71,11110,8
4,120000,2003,2015,내수동,경희궁 파크팰리스,12,24,146.33,95,11110,4
5,17000,2014,2015,연건동,이화에수풀,12,17,16.98,195-10,11110,8
6,17000,2014,2015,연건동,이화에수풀,12,18,16.98,195-10,11110,4
7,57000,2006,2015,명륜1가,렉스빌,12,29,106.98,19,11110,3
8,44000,1995,2015,명륜2가,아남1,12,1,84.8,4,11110,18
9,52000,1995,2015,명륜2가,아남1,12,10,84.9,4,11110,12
10,49800,1995,2015,명륜2가,아남1,12,19,84.8,4,11110,1
11,41000,1999,2015,명륜2가,아남3,12,19,61.13,237,11110,7
12,41000,1999,2015,창신동,두산,12,2,59.95,232,11110,9
13,39900,2003,2015,창신동,창신이수,12,3,68.06,23-816,11110,8
14,19500,1966,2015,창신동,동대문,12,3,28.8,328-17,11110,6
15,20800,1966,2015,창신동,동대문,12,7,28.8,328-17,11110,3
16,27200,1993,2015,창신동,창신쌍용2,12,7,64.66,703,11110,3
17,39000,1999,2015,창신동,두산,12,10,59.95,232,11110,14
18,39950,1993,2015,창신동,창신쌍용2,12,11,115.53,703,11110,2
19,34500,1992,2015,창신동,창신쌍용1,12,12,79.87,702,11110,5
20,37000,1992,2015,창신동,창신쌍용1,12,14,79.87,702,11110,3
21,42800,1992,2015,창신동,창신쌍용1,12,22,106.62,702,11110,12
22,37300,1992,2015,창신동,창신쌍용1,12,23,79.87,702,11110,9
23,50000,1999,2015,창신동,두산,12,24,84.9,232,11110,4
24,12300,2013,2015,숭인동,종로아인스빌,12,2,12.15,1392-1,11110,10
25,52000,2009,2015,숭인동,종로청계힐스테이트,12,3,84.9478,766,11110,19
26,42500,2009,2015,숭인동,종로청계힐스테이트,12,5,59.9426,766,11110,2
27,53300,2008,2015,숭인동,종로센트레빌,12,5,84.92,2-1,11110,10
28,11500,2014,2015,숭인동,숭인한양LEEPS,12,8,12.78,1421-2,11110,10
29,13000,2014,2015,숭인동,삼전솔하임4차,12,8,15.09,318-2,11110,15
30,27000,1997,2015,숭인동,"동문 (비동,씨동) (494-0)",12,9,59.94,494,11110,3
31,44900,2009,2015,숭인동,종로청계힐스테이트,12,14,59.9426,766,11110,12
32,11900,2014,2015,숭인동,숭인한양LEEPS,12,14,12.78,1421-2,11110,11
33,10000,2013,2015,숭인동,주건축물제1동,12,15,14.48,1392,11110,14
34,10500,2013,2015,숭인동,주건축물제1동,12,15,15.76,1392,11110,13
35,42500,2008,2015,숭인동,종로센트레빌,12,19,59.92,2-1,11110,12
36,39700,2008,2015,숭인동,종로센트레빌,12,22,59.92,2-1,11110,1
37,52300,2008,2015,숭인동,종로센트레빌,12,26,84.92,2-1,11110,12
38,10800,2013,2015,숭인동,종로유케이201,12,31,12.01,201-11,11110,7
39,52500,2009,2015,숭인동,종로청계힐스테이트,12,31,84.9478,766,11110,11
40,44600,1995,2015,교북동,동아,12,7,84.28,101,11110,10
41,115000,2004,2015,평창동,벽산블루밍평창힐스,12,2,210.53,45,11110,2
42,164500,2009,2015,평창동,롯데캐슬 로잔,12,3,219.775,108,11110,3
43,31500,1998,2015,평창동,삼성,12,6,59.97,596,11110,9
44,39490,2000,2015,무악동,현대,12,12,60,82,11110,15
45,63490,2000,2015,무악동,현대,12,15,114.9,82,11110,6
46,62000,2008,2015,무악동,인왕산아이파크,12,16,84.858,60,11110,5
47,63400,2015,2015,무악동,인왕산2차아이파크,12,22,84.0284,88,11110,10
48,61000,2008,2015,무악동,인왕산아이파크,12,25,84.858,60,11110,13

In [59]:
df.groupby(["년"])["거래금액"].agg(["mean"])

              mean
년
2015  47672.040816

In [60]:
#2.가장 비싸게 아파트가 거래된 금액 및 아파트이름
df["거래금액"].max()

164500

In [61]:
df["거래금액"].idxmax()

42

In [62]:
#시계열 탐색
#시계열에서 이상치탐지
#시계열 예측